services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.development

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    env_file:
      - ./frontend/.env.development
    depends_on:
      - backend